for test

diff --git a/.github/workflows/docker-build-publish.yml b/.github/workflows/docker-build-publish.yml
--- a/.github/workflows/docker-build-publish.yml
+++ b/.github/workflows/docker-build-publish.yml
@@ -4,68 +4,68 @@ on:
     types: [published]
 
 jobs:
-  dockle:
-    name: Dockle scan
-    runs-on: ubuntu-18.04
-    steps:
-      - uses: actions/checkout@master
-      - name: Build docker image
-        run: docker build ./ -t ${IMAGE_NAME} --file Dockerfile
-      - name: Install dockle
-        run: |
-          VERSION=$(curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | \
-          grep '"tag_name":' | \
-          sed -E 's/.*"v([^"]+)".*/\1/' \
-          )
-          curl -L -o dockle.deb https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.deb
-          sudo dpkg -i dockle.deb
-          rm dockle.deb
-      - name: Check image with dockle
-        run: dockle ${IMAGE_NAME}
-      - name: Slack Notification
-        uses: 8398a7/action-slack@v2
-        if: cancelled() || failure()
-        with:
-          status: ${{ job.status }}
-          author_name: Slime-hatena/sandbox
-          text: <!channel>
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
-    env:
-      IMAGE_NAME: slimehatena/sandbox
-  trivy:
-    name: Trivy scan
-    runs-on: ubuntu-18.04
-    steps:
-      - uses: actions/checkout@master
-      - name: Build docker image
-        run: docker build ./ -t ${IMAGE_NAME} --file Dockerfile
-      - name: Install trivy
-        run: |
-          sudo apt-get install apt-transport-https gnupg
-          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
-          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
-          sudo apt-get update
-          sudo apt-get install trivy
-      - name: Vulnerability scan with trivy
-        run: trivy --only-update alpine -q --severity HIGH,CRITICAL --exit-code 1 ${IMAGE_NAME}
-      - name: Slack Notification
-        uses: 8398a7/action-slack@v2
-        if: cancelled() || failure()
-        with:
-          status: ${{ job.status }}
-          author_name: Slime-hatena/sandbox
-          text: <!channel>
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
-    env:
-      IMAGE_NAME: slimehatena/sandbox
+  # dockle:
+  #   name: Dockle scan
+  #   runs-on: ubuntu-18.04
+  #   steps:
+  #     - uses: actions/checkout@master
+  #     - name: Build docker image
+  #       run: docker build ./ -t ${IMAGE_NAME} --file Dockerfile
+  #     - name: Install dockle
+  #       run: |
+  #         VERSION=$(curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | \
+  #         grep '"tag_name":' | \
+  #         sed -E 's/.*"v([^"]+)".*/\1/' \
+  #         )
+  #         curl -L -o dockle.deb https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.deb
+  #         sudo dpkg -i dockle.deb
+  #         rm dockle.deb
+  #     - name: Check image with dockle
+  #       run: dockle ${IMAGE_NAME}
+  #     - name: Slack Notification
+  #       uses: 8398a7/action-slack@v2
+  #       if: cancelled() || failure()
+  #       with:
+  #         status: ${{ job.status }}
+  #         author_name: Slime-hatena/sandbox
+  #         text: <!channel>
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
+  #   env:
+  #     IMAGE_NAME: slimehatena/sandbox
+  # trivy:
+  #   name: Trivy scan
+  #   runs-on: ubuntu-18.04
+  #   steps:
+  #     - uses: actions/checkout@master
+  #     - name: Build docker image
+  #       run: docker build ./ -t ${IMAGE_NAME} --file Dockerfile
+  #     - name: Install trivy
+  #       run: |
+  #         sudo apt-get install apt-transport-https gnupg
+  #         wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
+  #         echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
+  #         sudo apt-get update
+  #         sudo apt-get install trivy
+  #     - name: Vulnerability scan with trivy
+  #       run: trivy --only-update alpine -q --severity HIGH,CRITICAL --exit-code 1 ${IMAGE_NAME}
+  #     - name: Slack Notification
+  #       uses: 8398a7/action-slack@v2
+  #       if: cancelled() || failure()
+  #       with:
+  #         status: ${{ job.status }}
+  #         author_name: Slime-hatena/sandbox
+  #         text: <!channel>
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
+  #   env:
+  #     IMAGE_NAME: slimehatena/sandbox
   docker_hub:
     name: Publish to Docker Hub
     runs-on: ubuntu-18.04
-    needs: [dockle, trivy]
+    # needs: [dockle, trivy]
     steps:
       - uses: actions/checkout@master
       - name: Build docker image
